### ISSUE TITLE
Error code 1 during install

### ISSUE THREAD

**Issue by psharma04** [YunoHost-Apps/homeassistant_ynh#10]
Device: Raspberry Pi 3
Log: [Log-Home-Assistant-Yunohost.txt](https://github.com/YunoHost-Apps/homeassistant_ynh/files/4116361/Log-Home-Assistant-Yunohost.txt)

**Comment by ewilly** [comment]
Really strange...
What's your ynuohost version ? (`yunohost -v`)
what is the result of `cat /usr/share/yunohost/helpers.d/logging  | grep 'usage: ynh_script_progression'` ?
