### ISSUE TITLE
Certain pages (like "Integrations") don't load when logged on yunohost

### ISSUE THREAD

**Issue by maoterodapena** [YunoHost-Apps/homeassistant_ynh#114]
### Context

- Hardware: *Raspberry pi*
- YunoHost version: 4.3.6.3
- I have access to my server: trough SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using package version/branch: homessistant_ynh 2022.6.5-ynh1

### Steps to reproduce

Fresh install Homeassistant from webadmin
Follow homeassistant startup instructions (create user, etc...)
Go to Settings > Devices and services

### Expected behavior

To load de page

### Logs
on /var/log/homeassistant/homeassistant.log apears...

2022-06-16 18:11:45 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from <pc name> blah blah

There are some Error 401 (not authorized) on the network section in the browser developer tools 

### Workaround

I need to logout of my yunohost, and everything is working fine (you don't even re-login on homeassistant). Seems to be related with SSOwAuth, but I can't figure it out how both applications work.

**Comment by ewilly** [comment]
hi,
see [#issuecomment-1120274062](https://github.com/YunoHost-Apps/homeassistant_ynh/issues/77#issuecomment-1120274062)

**Comment by SpencerDub** [comment]
I am also getting this issue. I just updated Home Assistant to version 2022.7.6~ynh1, and when I log in and navigate to Settings - Integration, the page does not load. If I look in the log, I see:

```
2022-07-23 19:34:33 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from [...]
```

I have logged out and back in and I have cleared my cookies and cache. The issue still persists.

**Comment by barning** [comment]
Yes, same error for me. Deleting Cache & Cookies also not work. Changed also to different browsers.
