### ISSUE TITLE
Cannot upgrade from 2022.6.1~ynh1 to 2022.6.7~ynh1

### ISSUE THREAD

**Issue by navanchauhan** [YunoHost-Apps/homeassistant_ynh#118]
### Describe the bug

Upgrade to 2022.6.7~ynh1 failed

### Context

- Hardware: *Raspberry Pi (arm64) at home*
- YunoHost version: 11.0.7
- I have access to my server: *Through SSH and through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- If upgrading, current package version:  2022.6.1~ynh1

### Logs

https://paste.yunohost.org/raw/adurafozom

**Comment by ewilly** [comment]
Nothing relevant in the log... :-(
Did you try several times ?
