### ISSUE TITLE
Upgrade not successful

### ISSUE THREAD

**Issue by hovancik** [YunoHost-Apps/homeassistant_ynh#136]
### Context

- Hardware: *Raspberry Pi at home*
- YunoHost version: 11.0.9.14 (stable)
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

  YNH_APP_CURRENT_VERSION: 2022.7.7~ynh1
  YNH_APP_MANIFEST_VERSION: 2022.9.0~ynh1

### Steps to reproduce

Upgrade from YNH admin

### Expected behavior

success

### Logs
https://paste.yunohost.org/raw/xobayikeme

**Comment by hovancik** [comment]
Also, backup is not working

```
Sep 09 17:14:53 systemd[1]: Started Home Assistant.
Sep 09 17:14:53 systemd[30438]: homeassistant.service: Failed to locate executable /var/www/homeassistant/bin/hass: No such file or directory
Sep 09 17:14:53 systemd[30438]: homeassistant.service: Failed at step EXEC spawning /var/www/homeassistant/bin/hass: No such file or directory
Sep 09 17:14:53 systemd[1]: homeassistant.service: Main process exited, code=exited, status=203/EXEC
Sep 09 17:14:53 systemd[1]: homeassistant.service: Failed with result 'exit-code'.
```

**Comment by ewilly** [comment]
Upgrade failed during the python upgrade, unfortunately without giving error log...
Regarding the restoration could you check if  the file exist `/var/www/homeassistant/bin/hass` ? 
If yes what is the output of those commands :
- `head -n 1 /var/www/homeassistant/bin/hass`
- `ls -l /var/www/homeassistant/bin/python3.9`

**Comment by hovancik** [comment]
I tried the upgrade again and it seems it fixed the old version. https://paste.yunohost.org/raw/xicimorovo

 A bit confused but YNH says I need to upgrade Home Assistant (homeassistant) from 2022.7.7~ynh1 to 2022.9.0~ynh1

**Comment by hovancik** [comment]
Latest version worked fine.
