### ISSUE TITLE
Python 3.9 no longer supported for Home Asistant >=2023.2

### ISSUE THREAD

**Issue by jedie** [YunoHost-Apps/homeassistant_ynh#159]
I see this warning now:
![grafik](https://user-images.githubusercontent.com/71315/206843322-2708dba5-ac98-4e1f-ac46-f7606ace82fd.png)

It just says that Home Asistant >=2023.2 will need Python 3.10

YunoHost used python from Debian repository. So we have to stuck with 3.9 until a new Debian Release is used, isn't it?
How to handle this? 
Use pyenv to install a own Python ? Use docker? Any idea?

EDIT: I create https://forum.yunohost.org/t/use-newer-python-than-3-9/22568 to discuss on a generic level, how to use a newer Python version...

**Comment by ewilly** [comment]
Thanks for you message.
I directly reply in the forum discussion.
