### ISSUE TITLE
setup country in configuration.yaml ?!?

### ISSUE THREAD

**Issue by jedie** [YunoHost-Apps/homeassistant_ynh#160]
I see this warning:
![grafik](https://user-images.githubusercontent.com/71315/206846158-99cc42b8-003f-4fd7-823e-7e42c4365842.png)
I says:

> No country has been configured.

But i can't change settings under `/config/general`:

![grafik](https://user-images.githubusercontent.com/71315/206846490-5d5d252f-5156-4be2-abd2-e4c4420a9d31.png)

Because:

> Editor disabled, because the configuration is stored in configuration.yaml.

It seems that https://github.com/YunoHost-Apps/homeassistant_ynh/blob/master/conf/homeassistant_conf_files/configuration.yaml doesn't has anything related to country, isn't it?

**Comment by ewilly** [comment]
Thanks for your feedback.
Once again a disturbing warning message from ha...
To integer homeassistant with yunohost LDAP directory we need the configuration.yaml. And as it exist some settings cant be done through the UI and have to be done manually directly in that file.
More information how to solve it here : [https://community.home-assistant.io/t/the-country-has-not-been-configured/498215](https://community.home-assistant.io/t/the-country-has-not-been-configured/498215)

**Comment by ewilly** [comment]
Will be fixed for new installation in the next app update (default set to FR = France).
[https://github.com/YunoHost-Apps/homeassistant_ynh/commit/5d4da2ca133256139669d784723561148930ec04](https://github.com/YunoHost-Apps/homeassistant_ynh/commit/5d4da2ca133256139669d784723561148930ec04)

**Comment by jedie** [comment]
Thats a bad idea. What's about yunohost config panel?

**Comment by ewilly** [comment]
Feel free to propose a PR

**Comment by ewilly** [comment]
Done see #166
