### ISSUE TITLE
Error: "Unauthorized" when adding device.

### ISSUE THREAD

**Issue by chexxor** [YunoHost-Apps/homeassistant_ynh#161]
### Describe the bug

Error message when trying to do most things in the Home Assistant web console.

### Context

- Hardware: HP Mini PC
- YunoHost version:  11.0.10.2
- I have access to my server: SSH, webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using HomeAssistant_ynh version: 2022.12.0~ynh1

### Steps to reproduce

- Open the "/config/integrations" page, then click the button to add a new device.
- Get error message on the web page: "Config flow could not be loaded: 401: Unauthorized"
- Look at the Network Log in the browser console to see this:
-- Request: POST /api/config/config_entries/flow
-- Response: 401 Unauthorized

### Expected behavior

I expect to be able to add a device to my Home Assistant installation.

### Resolution

After much research, I discovered this solution:
- Login to my Yunohost machine
- Run this command
-- `$ yunohost app setting homeassistant skipped_uris --value="/api/"`

I believe this tells SSOWat to ignore API requests.

I think we need to add this line to the installation script:

`ynh_app_setting_set --app=$app --key=skipped_uris --value="/api/"`

**Comment by chexxor** [comment]
Related to:
- https://github.com/YunoHost-Apps/homeassistant_ynh/issues/114
- https://github.com/YunoHost-Apps/homeassistant_ynh/issues/77

Fix inspired by: https://github.com/YunoHost-Apps/portainer_ynh/pull/14/commits/96e990b598a7b336ac5a763c5bff2c18a59a6549

**Comment by ewilly** [comment]
Thanks for your feedback and your PR !!
I made some comments in you PR.
