### ISSUE TITLE
Default home location is in Africa

### ISSUE THREAD

**Issue by cichy1173** [YunoHost-Apps/homeassistant_ynh#165]
Hi. I see that default home location is in Africa and I can't change it via web panel.
![obraz](https://user-images.githubusercontent.com/32648503/208085125-33089d48-00f2-423a-8962-2f3efeb96505.png)

Is there a possibility to change that? I want to set up my default home location.

**Comment by ewilly** [comment]
Not possible via web panel, you have to manually edit the file `/home/yunohost.app/homeassistant/configuration.yaml`.
See here for the variables [https://www.home-assistant.io/docs/configuration/basic/](https://www.home-assistant.io/docs/configuration/basic/)
