### ISSUE TITLE
Homeassistant : installation failed

### ISSUE THREAD

**Issue by davidszerman** [YunoHost-Apps/homeassistant_ynh#167]
Hello,

I tried to install HomeAssistant but it fails 

https://paste.yunohost.org/raw/zewohoxehu

Thank you for your help

**Comment by ewilly** [comment]
Next time please follow the issue template...
Can you try to install the app with this path `https://github.com/YunoHost-Apps/homeassistant_ynh/tree/debug`

**Comment by davidszerman** [comment]
Hello, 

Thanks ; here is the detailed log : https://paste.yunohost.org/raw/payidagixu

**Comment by ewilly** [comment]
Hummm you are still on buster and your rustc version is deprecated...
Homeassistant need so many uptodate requirements it still hard to maintain with debian stable... I can't figure how to manage that with debian buster.
