### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by bauerbyter** [YunoHost-Apps/homeassistant_ynh#168]
### Describe the bug

Installation Aborts, see logs

### Context

- Hardware: Raspberry Pi at home 
- YunoHost version:current
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce
 - Install through UI

### Logs

https://paste.yunohost.org/raw/isozuqekey

**Comment by ewilly** [comment]
Debian buster 
Closing as duplicate of #167
