### ISSUE TITLE
Local access to Home Assistant

### ISSUE THREAD

**Issue by cichy1173** [YunoHost-Apps/homeassistant_ynh#180]
Hi. Home Assistant can be used locally without internet access but in Yunohost it is not configured. **How to configure it?**

### Context

- Hardware: Mini PC HP 800 G3 Mini with Yunohost 11.0.11 stable
- I have access to my server: ssh and admin panel
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 

### Expected behavior

Local access to Home Assistant installed with Yunohost.

**Comment by tituspijean** [comment]
I have no issue accessing Home Assistant from my local network.
Please explain what is not working with your instance.

**Comment by cichy1173** [comment]
> I have no issue accessing Home Assistant from my local network. Please explain what is not working with your instance.

How did you configure it? And what do you write in browser to access locally?

**Comment by ewilly** [comment]
If it directly on the machine where yunohost is installed : `localhost:8123` if 8123 is the port defined as `server_port` in your `/home/yunohost.app/homeassistant/configuration.yaml`

**Comment by cichy1173** [comment]
@ewilly 
I host Home Assistant on Mini PC and I want to have access in my local network. Opening `local_minipc_address:8123` in browser does not work. But Home Assistant Android detects that Home Assistant exists in local network so it should be possible.

**Comment by tituspijean** [comment]
> How did you configure it? And what do you write in browser to access locally?

You should be the one writing that out. :)

My setup is; app installed on `hass.local` domain for local access and reverse-proxy on external VPS for remote access to `hass.mydomain.example`.
*However*, if you are not exposed to hairpinning issues (cf. YunoHost's documentation), you should be able to reach your instance with its domain.

So:

1. What's its domain/path?
2. When you input these on your domain, what's the error? Check out your browser console with F12, in Console and Network tabs.

**Comment by cichy1173** [comment]
> That might work if you open the port in YunoHost's firewall, but do not EVER open the port on your modem. That will expose your app over the internet without encryption.

That was something that I was looking for! Thank you. I just only wanted that to have local access in situation when I do not have internet connection.  

>  What's its domain/path? When you input these on your domain, what's the error? Check out your browser console with F12, in Console and Network tabs.

I can access home assistant via external URL (I have domain bought in Gandi) even if I am in the same network with my yunohost computer. I don't have hairpinning issue (I know what is it because it is something that my brother had).

**Comment by tituspijean** [comment]
Another solution (to not rely on the IP address) could be to have your own DNS records setup within your router or by using your own local DNS resolver.

Closing as solved. :)

**Comment by cichy1173** [comment]
I have Pi-hole with Unbound so I will try something with that  :-). Thanks.
