### ISSUE TITLE
Installing a custom libffi creates epic debugging hell ...

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/homeassistant_ynh#182]
So i just spent at least 2 or 3 hours debugging a user's system which was just throwing `Illegal instructions` for any code trying to import OpenSSL's libs ... And after some mental sanity point loss we managed to pinpoint to the system having a special `/usr/local/lib/libffi.so.whatever` file ... and after checking the timestamp with the yunohost logs, to the install/upgrade of homeassistant 9 months-ish ago ...

So I ended up finding https://github.com/YunoHost-Apps/homeassistant_ynh/pull/72 and https://github.com/YunoHost-Apps/homeassistant_ynh/issues/69

This looks like super bad practice to yolo-install a custom version of such a critical lib on the system ... this will surely create more inconsistencies between openssl and libffi installed version in the future ...

Can you elaborate on the motivations of this

**Comment by ewilly** [comment]
autant que je me rappelle c'était lié à un pb spécifique lié a Raspbian car avec Debian l'install sans ce build fonctionnait les CI passaient également . Ce workaround était suggérer sur le forum de homeassistant. Sans le symlink vers /usr/local/lib/libffi.so j'aurais pas pensé que ca puisse poser problème.
Avec bullseye je peux enlever ce build des fichiers install.
A l'vanir si un tel cas ce produit est-il préféreable d'exclure une architecture ou as-tu un autre conseil ?

**Comment by alexAubin** [comment]
Dans tout les cas le truc est d'essayer autant que possible d'installer des trucs "en global" qui ne sont pas facilement enlevable et/où dont on ne peut pas identifier de quelle app ça vient. Par exemple les dépendances apt sont globales, mais on peut retrouver quel dépendance `$app-ynh-deps` en a besoin, et apt gère correctement la désinstallation du machin si y'en a plus besoin. 

Par contre les trucs genre `pip install` en global (= pas dans un venv) ont tendance à foutre un gros zbeul, et tu ne peux pas du tout faire un `pip uninstall` puisque aucune garantie qu'une autre app n'utilise pas le truc.

Bon ici c'est un cas super spécifique puisqu'il s'agit carrément de rajouter une lib custom ... Pour ça il faut connaître un peu plus le schmilblik des librairies et sans doute installer la lib genre dans `/var/www/$app/customlib/` puis ensuite jouer avec la variable `LD_LIBRARY_PATH` pour inclure `/var/www/$app/customlib` dedans de sorte que cette lib ne soit utilisée exclusivement que par le process qui en a besoin ...

**Comment by ewilly** [comment]
Merci pour l'idée.
En attendant j'ai supprimé cette compilation : [https://github.com/YunoHost-Apps/homeassistant_ynh/commit/451c86af3a1cdebae0f386b23e6b63f7a565eda6](https://github.com/YunoHost-Apps/homeassistant_ynh/commit/451c86af3a1cdebae0f386b23e6b63f7a565eda6)
