### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/homeassistant_ynh#19]
I followed the documentation and HA installed fine with no hiccups. I get to the login page — in this case its test.URL.com. Nothing else installed on it. When I type in my YNH credentials it refuses them. I've also tried admin and pw, the HA default of root/blank and some others. Any insight?

**Comment by ewilly** [comment]
Your're right -> fix by #20

**Comment by brimwats** [comment]
thanks!
