### ISSUE TITLE
Be more precise on fail2ban rule

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/homeassistant_ynh#195]
### Describe the bug

*Fail2ban is being too aggressive on banning IP with the current setting due to a bug on Home Assistant*

See that topic about the issue: https://community.home-assistant.io/t/wth-are-those-login-attempt-failed/219519/65

With my current configuration I'm getting banned every time I open a dashboard, and thus end up being banned as a recidivist.
Mainly I'm banned from */api* access due to the dashboard itself.
Hopefully I know how to unban myself...

Trying to solve that issue without loosing fail2ban protection I'm trying that filter rule:
```
failregex = Login attempt or request with invalid authentication from <HOST> .* Requested URL: ./auth/
```
It work so far by not banning me from normal use of the app but ban me if I try to brute force the authentication.

**Comment by ewilly** [comment]
Failregex update and merged (#208)
