### ISSUE TITLE
Installation failled Could not find platform dependent libraries <exec_prefix>

### ISSUE THREAD

**Issue by laguill** [YunoHost-Apps/homeassistant_ynh#217]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to the app itself. Refer to its documentation or repository for help.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug

*A clear and concise description of what the bug is.*

### Context

- Hardware: Old laptop
- YunoHost version: 11.1.19
- I have access to my server: Through SSH and through the webadmin and direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: I have a nextcloud instance on mydomain.nohost.me and I added a subdomain to install home assistant hass.mydomain.nohost.me
- Using, or trying to install package version: home assistant
### Steps to reproduce

I tried to install home assistant with the web admin interface of yunohost

### Logs
https://paste.yunohost.org/raw/opocesiqip

**Comment by ewilly** [comment]
hello,
you have an issue with your venv environnement because the command `sudo -u homeassistant /usr/local/bin/python3.10 -m venv --without-pip /var/www/homeassistant` is failing.
Best way is to reinstall the app.

**Comment by laguill** [comment]
The app is not install
I don't understand what you mean by reinstalling the app
Everything I did was clicking on the install button to install homeassistant on the admin page

**Comment by ewilly** [comment]
Humm seems your log does not correspond to a fresh installa dn the previous seems corrupted. If the app is not install please remove those with with the following commands:
`rm /usr/local/bin/python3.10*`
`rm -R /var/www/homeassistant`
`rm -R /home/yunohost.app/homeassistant`
and reinstall.
