### ISSUE TITLE
Install addons

### ISSUE THREAD

**Issue by laguill** [YunoHost-Apps/homeassistant_ynh#220]
Hello,

How can I modify my location in home assistant GUI ?
Is it possible to add addons like mosquitto, node red and file editor ?

**Comment by ewilly** [comment]
hello,

> How can I modify my location in home assistant GUI ?

you can't with GUI, you have to manually edit the file `/home/yunohost.app/homeassistant/configuration.yaml`

>  Is it possible to add addons like mosquitto, node red and file editor ?

If not availbale in default integrations (see [https://www.home-assistant.io/integrations/#all](https://www.home-assistant.io/integrations/#all) take a look at HACS (see [https://hacs.xyz/](https://hacs.xyz/)

**Comment by laguill** [comment]
I used this script in '/home/yunohost.app/homeassistant' on my server in ssh in '/home/yunohost.app/homeassistant'

After cleaning the cache cache of my brother I get this error (see print screen bellow).
Also I tried in private browser but i get the same error.

![image](https://github.com/YunoHost-Apps/homeassistant_ynh/assets/74424947/5ef1d64d-9770-4072-890b-3e57909aebc3)
