### ISSUE TITLE
First login problem

### ISSUE THREAD

**Issue by Flamigni** [YunoHost-Apps/homeassistant_ynh#257]
Hello,

After a fresh install of HA on Yunohost, i can not login.
I used my SSO login but i keep having the message "invalid username or password".

It seems that i have not the onboarding screen to create the admin user : i don't see the message "You are about to give access https://xxxxx to your Home Assistant instance" on my login screen.

Could you help me ? 
Thank you :)

**Comment by ewilly** [comment]
hello,
did you modify `/home/yunohost.app/homeassistant/configuration.yaml` ?
did you edit the permissions of the app ? (All users should have access)

**Comment by Flamigni** [comment]
Hello Ewilly,

No I have not modified this file : i will check the permissions.
At the beginning of the install, should I use all users ?

I tried to install again several times and have the same result.
I don't understand because I installed an older version a few weeks ago and it worked.

**Comment by ewilly** [comment]
Hi,
did you solved your issue ?

**Comment by Flamigni** [comment]
Hello Ewilly,
No the problem is not solved, i am waiting for a new screen to test the permissions.
I keep you in touch :)

**Comment by kostya-fr** [comment]
Hey I have the same issue after login with SSO, HA ask me to login again, but I don't have this password. 
There is a configuration for `configuration.yaml` ?

**Comment by Flamigni** [comment]
Problem solved, I put a wrong time zone code ....
With the right one, I have been able to login with SSO account
