### ISSUE TITLE
Mauvais niveau dans apps.json ?

### ISSUE THREAD

**Issue by dystopy** [YunoHost-Apps/homeassistant_ynh#32]
Bonjour à tous,

Grand débutant devant l'éternel, je vais peut-être poser une question bête, merci de m'en excuser si c'est le cas :)

J'ai l'impression que le dernier pull request qui a été fait (et aboutit sur une validation de l'application) n'a pas été pris en compte dans le fichier apps.json. De ce fait, je ne peux pas mettre à jour mon instance de Homeassistant.

Ou alors ça n'a rien à voir ?

Merci en tous cas pour le boulot fait !

**Comment by tituspijean** [comment]
Bonjour !

Le fichier `apps.json` est mis à jour automatiquement une fois par semaine, la *Pull Request* est générée le vendredi soir généralement. Il suffit de patienter, ou de lancer la commande à la main. 😉 

`sudo yunohost app upgrade homeassistant -u https://github.com/YunoHost-Apps/homeassistant_ynh/tree/master`

**Comment by dystopy** [comment]
Waouh, ça c'est une réponse rapide ! 

Merci beaucoup, c'est bien noté ! (un quelconque risque à lancer la commande à la main ou ça revient au même qu'à faire l'upgrade depuis l'interface ?)

**Comment by tituspijean** [comment]
C'est équivalent. Et au cas où, ça fait une sauvegarde avant.
