### ISSUE TITLE
problem access tab "intégration"

### ISSUE THREAD

**Issue by enamaryn** [YunoHost-Apps/homeassistant_ynh#33]
Bonjour,

J'ai installé home assistant via le panneau administration de YunoHost sur un sous domaine. Pas de problème à l'installation, aucune erreur dans les logs.

Maintenant je souhaite ajouter m'a domotique via l'onglet intégration mais cela tourne en boucle sans jamais afficher quoi que se soit.

Une idée ? Je me demande si je suis bien administrateur du coup... comment le vérifier ?

<img width="1279" alt="Capture d’écran 2021-07-22 à 10 36 54" src="https://user-images.githubusercontent.com/40593656/126611433-938df9f5-86ce-4295-a9e6-f17bba634f3d.png">

**Comment by enamaryn** [comment]
l'onglet intégration fonctionne avec l'application Home Assistant sur iOS. Bizarre. J'ai tenté de changer de navigateur, safari et chrome pareil.

**Comment by tituspijean** [comment]
Peux-tu regarder si tu as des erreurs dans le console de ton navigateur lorsque tu recharges la page? (touche F12)

**Comment by enamaryn** [comment]
Erreur 401, dans le doute j'ai regenerer le certificat ssl... c'est on jamais. En PJ
<img width="1279" alt="Capture d’écran 2021-07-22 à 15 27 43" src="https://user-images.githubusercontent.com/40593656/126646914-be32e6e1-4a82-40c6-88a9-e39c6e17e4a8.png">

**Comment by enamaryn** [comment]
Pas d'idées ?

**Comment by ewilly** [comment]
Etrange je ne rencontre pas ce problème. As-tu essayer de supprimer ton cache ?

**Comment by t0bybr** [comment]
I have the same problem and nothing I found, helped. Still getting a 401 on the devices page and when trying to add an user. Is there anything I can do about it? Thanks.
