### ISSUE TITLE
Homekit Bridge only able to connect after opening Homekit port

### ISSUE THREAD

**Issue by grahamalama** [YunoHost-Apps/homeassistant_ynh#337]
Posting this as an issue to hopefully help the next person who tries to enable this integration on YNH.

### Describe the bug

I had to open port `21065` to successfully add the Homekit Bridge to Home Assistant through YNH.

```
yunohost firewall allow Both 21064
```

### Context

- Hardware: Raspberry Pi at home
- YunoHost version:  11.2.12
- Application version: 2024.5.5~ynh1
- I have access to my server: Through SSH, through the webadmin

### Steps to reproduce
- Add Homekit Bridge integration
- Follow instructions to add bridge to home

### Expected behavior
The pairing is successful

### Actual behavior
The pairing does not complete.

Like mentioned above, I was able to make this work by opening port 21064 (the default port used by Homekit). I used `both`, but I'm guessing only the TCP port is enabled

**Comment by ewilly** [comment]
As it's not an issue but a specific customization, i close it.
