### ISSUE TITLE
Support add-ons like ESPHome

### ISSUE THREAD

**Issue by Gredin67** [YunoHost-Apps/homeassistant_ynh#349]
Current "core" installation method does not provide support for add-ons such a ESPHome
See https://github.com/chexxor/esphome_dashboard_ynh

**Comment by ewilly** [comment]
Only core can be package for yunohost, if you want an other version you need to create a VM.

**Comment by Gredin67** [comment]
what about linking to the ESPHome repo in this repo when the App will be available and tested ?

**Comment by ewilly** [comment]
ESP Home integration can  be add as integration, see [https://www.home-assistant.io/integrations/esphome](https://www.home-assistant.io/integrations/esphome) and seems working with core install.
