### ISSUE TITLE
Upgrade during virualenv rebuild fails, then restore fails after Bookworm migration

### ISSUE THREAD

**Issue by lyynd** [YunoHost-Apps/homeassistant_ynh#394]
### Describe the bug

Symptoms are similar to https://github.com/YunoHost-Apps/homeassistant_ynh/issues/360, but errors in logs are different, so I think a separate issue is appropriate.
`0030_rebuild_python_venv_in_bookworm` thinks that it should handle `homeassistant` and fails, and then restoring fails as well.

### Context

- Hardware: x86_64 mini PC
- YunoHost version: 12.0.6
- I have access to my server: `incus shell`
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 2024.10.4~ynh1
- If upgrading, current package version: 2024.10.4~ynh1

### Steps to reproduce

- Perform migration to bookworm (`0027_migrate_to_bookworm`).
- Perform virtualenv migration (`0030_rebuild_python_venv_in_bookworm`).

### Expected behavior

Home Assistant is still installed and works.

### Logs

Failed upgrade log: https://paste.yunohost.org/raw/uvezorimix
Failed restore log: https://paste.yunohost.org/raw/iqimuzavuc

**Comment by chexxor** [comment]
I also experienced that failed restore:
`Exception: Original path for "/home/yunohost.app/homeassistant" not found`

However, my HomeAssistant installation is reporting as being not installed, and restore from backup fails.

**Comment by ewilly** [comment]
Reorted and mentionned [here](https://forum.yunohost.org/t/yunohost-12-0-beta-bookworm/30496/84). Have to check

**Comment by lyynd** [comment]
> However, my HomeAssistant installation is reporting as being not installed, and restore from backup fails.
Yes, before restoring the app is deleted, so if restoring fails the app will be missing.

**Comment by lyynd** [comment]
Actually, what I have dove was running `yunohost app upgrade --force homeassistant` before the migration (since I knew it will be problematic because this was the second attempt to upgrade to bookworm), and this succeeds. Then the migration will say that it could not rebuild `homeassistant`'s virtualenv and suggest upgrading again, and this time upgrading fails.

**Comment by chexxor** [comment]
The workaround I did was to simply re-install HomeAssistant from the Yunohost app catalog. It looks like all my settings were found and work correctly in the re-installed instance.

**Comment by ewilly** [comment]
issue reported upstream https://github.com/YunoHost/yunohost/pull/1996
