### ISSUE TITLE
/bin/bash: BASH_XTRACEFD: 7: cannot open as FILE

### ISSUE THREAD

**Issue by Soowarez** [YunoHost-Apps/homeassistant_ynh#45]
Hello,

I have an error when I try to install Home Assistant on my YunoHost instance.

Hardware: 

Raspberry pi 3B+
YunoHost 4.3.5 (stable)

After 20 minutes I still have this error: 

[https://i.goopics.net/sjguos.png](url)

Thanks

**Comment by Soowarez** [comment]
Log:
[https://textup.fr/606144OJ](url)

**Comment by ewilly** [comment]
something wen wrongon your server side during the install
please retry to install

**Comment by arofarn** [comment]
Same warnings here when updating from homeassistant 2021.12.8~ynh1 to 2021.12.10~ynh1 but they did not stop the update and the 2021.12.10 seems to works as intended.

When looked in yunohost-api.log file, I have found that the update to 2021.12.8 few days ago throws the same warning, without blocking the update.

[hass-update-warnings.txt](https://github.com/YunoHost-Apps/homeassistant_ynh/files/7917937/hass-update-warnings.txt)
.

**Comment by ewilly** [comment]
as mentioned here "just don’t worry about it …" ([link](https://forum.yunohost.org/t/bin-sh-bash-xtracefd-7-invalid-value-for-trace-file-descriptor/5878/5))
