### ISSUE TITLE
Update Loop with HA

### ISSUE THREAD

**Issue by brimwats1** [YunoHost-Apps/homeassistant_ynh#54]
I've been trying to update HA and a couple other apps for a few days but all that happens is that it fails and then shows up again in the "to update" 

logs : https://paste.yunohost.org/raw/zajagebena

my YNH is the most recent (worry I don't have the # rn) and it's on a Dell R710

**Comment by ewilly** [comment]
`ERROR 1007 (HY000) at line 1: Can't create database 'homeassistant'; database exists`
seams you made first a partial update that fails after creating the sql database. Before upgrading you now have to delete that database. You can do it with that command : 
`source /usr/share/yunohost/helpers && ynh_mysql_remove_db --db_user=homeassistant --db_name=homeassistant`
