### ISSUE TITLE
Repeated database los

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/homeassistant_ynh#55]
Hello!

see also #54 — i keep losing the database and have to erase it when updating HA. Any insight?

logs: https://paste.yunohost.org/raw/ebetipitik

**Comment by ewilly** [comment]
Still the same issue as #54 : `2022-01-29 21:41:02,948: WARNING - ERROR 1007 (HY000) at line 1: Can't create database 'homeassistant'; database exists`
Did you delete the db as i suggest you ?
You can do it by using the app [phpmyadmin](https://install-app.yunohost.org/?app=phpmyadmin) (select the homeassistant db > operations > Remove database)

**Comment by brimwats** [comment]
@ewilly yeah I deleted it exactly as you said, and then it worked again, but the next update it was broken again. I'll try phpmyadmin this time!

**Comment by brimwats** [comment]
I deleted the database like you suggested, and then tried to update. It failed again: https://paste.yunohost.org/raw/buraxaqubu

**Comment by brimwats** [comment]
(am going to try removing and reinstalling)

**Comment by brimwats** [comment]
okay it failed again because of the database in var/www...so then I went and deleted it again with phpmyadmin and tried a clean install...and then it failed again https://paste.yunohost.org/raw/epimugimeq

**Comment by ewilly** [comment]
why a clean install ??? you just had to manually delete the database and upgrade to new version...
Now, is the app still installed ? if not manually delete the directory: `/var/www/homeassistant`

**Comment by brimwats** [comment]
> why a clean install ??? 

because I **did** delete the database and upgrade to a new version and it still failed

this time i sshed in, did `sudo rm -rf /var/www/homeassistant`

then i went back webadmin and installed homeassistant again

this time it worked—but i wanted to make sure that I wasn't going to lose it all again next update

**Comment by ewilly** [comment]
sorry can't figure out what append to you previous install/upgrade to fail in such a middle way between old and new version. That's not due to the app itself (all the test well passed) but due to something that append on your server side.

**Comment by ewilly** [comment]
anyway good news to see your homeassistant working again (don't hesitate to make a backup when configured) :)
