### ISSUE TITLE
Supervised?

### ISSUE THREAD

**Issue by colmoneill** [YunoHost-Apps/homeassistant_ynh#68]
Hello,

Thank you for this version of HA on YNH.
I have been starting some research on HA and it seems that most addons require Home-Assistant Supervised to work fully.

In theory, would it be possible to run Home Assistant Supervised on a YNH server? I'm unfamiliar with the specific requirements, but wondered if it might conflict with other docker containers or the likes.

Thank you and best regards

**Comment by ewilly** [comment]
Can't be done on Yunohost because the operating system have to be dedicated to running Home Assistant Supervised only.
