### ISSUE TITLE
Can not update from 2021.6.5~ynh1

### ISSUE THREAD

**Issue by shizzlemo** [YunoHost-Apps/homeassistant_ynh#69]
Hi,

I tried to update the december version and the one from february, but installation always fails. Something seems to be wrong with the frontend.

Can somebody help me and get me a hint, what could be wrong? 

https://paste.yunohost.org/uqanogasos

Thanks in advance.

**Comment by ewilly** [comment]
Need to compile new version of libffi. It's normally fix in testing branch.
Or you could manually buid it and restart Homeassistant after
`wget "https://github.com/libffi/libffi/releases/download/v3.3/libffi-3.3.tar.gz"`
`tar zxf libffi-3.3.tar.gz`
`cd libffi-3.3`
`./configure`
`sudo make install`
`sudo ldconfig`

**Comment by shizzlemo** [comment]
Hi,
thanks for your help. I did the steps you advised.  Now I'm getting other errors.

https://paste.yunohost.org/oxorematak

**Comment by shizzlemo** [comment]
Did another Update after your actions and now it seems to run. Thanks!
