### ISSUE TITLE
Availability of custom path in url

### ISSUE THREAD

**Issue by Tropicao** [YunoHost-Apps/homeassistant_ynh#7]
Hi,
I am currently playing a bit with Home assistant in Yunohost (I was glad to find this integration !), but since its default path is "/", it prevents me from installing any other app on my server. It would be nice to be able to change the url path of Home assistant on server, for example https://myserver.com/hass, instead of forcing https://myserver.com as default.
I would be glad to give some help on this point (I tried to clone and customize the repo, but I am struggling to properly expose the app on customized url)

**Comment by ewilly** [comment]
Hi,
sorry for the late response. Homeassistant is not actually availlable to work from a path (see https://github.com/home-assistant/architecture/issues/156#issuecomment-478183627)

**Comment by Tropicao** [comment]
Hi,
ok, thanks for the details, I did not know it was as dependant on HA architecture, I thought it was only matter of redirecting properly nginx on yunohost side.
