### ISSUE TITLE
Upgrade failing from 2021.11.4~ynh1 to 2022.2.9~ynh1 - missing /home/yunohost.app/homeassistant/configuration.yaml

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/homeassistant_ynh#70]
### Describe the bug

Upgrade is failing on the `sed` trying to replace a value in a configuration that doesn't seem to be in the right place (/home/yunohost.app/homeassistant/.homeassistant/configuration.yaml is present, not /home/yunohost.app/homeassistant/configuration.yaml) 

### Context

- Hardware: *Old computer*
- YunoHost version: 4.4.0
- I have access to my server: *Through SSH , through the webadmin,  direct access via keyboard / screen *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

```sh
    yunohost app upgrade homeassistant
```

### Expected behavior

For the upgrade to succeed and handle moving or better detection of the existing configuration 
/home/yunohost.app/homeassistant/configuration.yaml

### Logs

Complete logs : https://paste.yunohost.org/raw/ujexebebom

**Comment by arthurlutz** [comment]
Trying to replay this failed upgrade gives another error : it can't create the `homeassistant` mysql database, so one needs to DROP it to go forward. Maybe this could be handled in the "oh failed upgrade, remove changes we've made so far" ?

**Comment by arthurlutz** [comment]
Trying to do a copy of the missing file, `cp -rv /home/yunohost.app/homeassistant/.homeassistant/configuration.yaml /home/yunohost.app/homeassistant/configuration.yaml`, I got a different error : https://paste.yunohost.org/raw/yetesamuki

**Comment by ewilly** [comment]
Could you give me the result of `ls -ali /var/www/homeassistant` ?

**Comment by arthurlutz** [comment]
Thanks for taking a look at this! 

```
ls -ali /var/www/homeassistant
total 32
5432079 drwxr-xr-x   6          1002 1002 4096 Dec  6 20:11 .
5637218 drwxr-xr-x+ 27 www-data      root 4096 Feb 20 11:29 ..
5432199 drwxr-xr-x   3          1002 1002 4096 Feb 20 11:16 bin
5432080 drwxr-xr-x   3          1002 1002 4096 Dec  5 21:15 include
5432081 drwxr-xr-x   4          1002 1002 4096 Dec  6 11:48 lib
5393325 lrwxrwxrwx   1          1002 1002    3 Dec  5 21:09 lib64 -> lib
5478724 -rw-r--r--   1          1002 1002 1065 Dec  6 20:11 LICENSE
5393326 -rw-r--r--   1 homeassistant 1002   75 Feb 21 14:23 pyvenv.cfg
5481315 drwxr-xr-x   3          1002 1002 4096 Dec  5 21:17 share
```

**Comment by arthurlutz** [comment]
While trying to debug, and run the commands outside of the upgrade script, I did do a `chown homeassistant /var/www/homeassistant` and did a pip upgrade I think (it wasn't seing the 2022 version of homeassistant). 

I have some the following log in the `homeassistant.log` :  

```
2022-02-21 15:14:24 WARNING (Recorder) [homeassistant.components.recorder.util] Version 3.27.2 of SQLite is not supported; minimum supported version is 3.31.0. Starting with Home Assistant 2022.2 this will prevent the recorder from starting. Please upgrade your database software before then
```
With buster (current yunohost stable) that  might be a problem since libsqlite3-dev is stuck on 3.27 : https://packages.debian.org/search?keywords=libsqlite3-dev

**Comment by ewilly** [comment]
The upgrade is designed to move to mariadb but now you are between old and new architecture which is quite  hard to correct. I suggest you to backup your config, uninstall ans reinstall from command line
