### ISSUE TITLE
401 Unauthorized error

### ISSUE THREAD

**Issue by t0bybr** [YunoHost-Apps/homeassistant_ynh#77]
Hi,

I'm using the latest version and have the problem, that when I want to add another user or when I try to load the integrationes page, I get an 401 error in the console and I can't do anything.
I restarted the server but it didn't help.

Do you have an idea what is causing the error?

Thanks in advance.
t0bybr

**Comment by ewilly** [comment]
Hi,
default configuration allow only ynh users to log in. You can manually change auth type in your configuration but you will loose the link between yunohost users and homeassistant users.
For intergrations i don't encounter any issue on my side and as you are the only one...

**Comment by ewilly** [comment]
clearing cache & deleting cookies issu needed
