### ISSUE TITLE
Cannot install due to Python version requirement

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/homeassistant_ynh#8]
I have just tried to reinstall the app, and I'm facing this error during installation:

 ```
WARNING - homeassistant requires Python '>=3.6.0' but the running Python is 3.5.3
```

YNH version 3.6.4.6

**Comment by ewilly** [comment]
Normally last commits fix that, I just forgot to update the community list. Either wait for the merge of [https://github.com/YunoHost/apps/pull/826] or install directly with `sudo yunohost app install https://github.com/YunoHost-Apps/homeassistant_ynh`

**Comment by julienguyonnet** [comment]
Hello,
FYI, I still have the same issue with a fresh install of YunoHost (3.6.5.3) despite trying from app gallery or ssh.
Rgds

**Comment by ewilly** [comment]
You are right. Some dependencies requires now python > 3.5.
I don't know how to solve it without either moving forward with buster or compiling python 3.6
App is broken

**Comment by ewilly** [comment]
Solved by migrating Yunohost to buster
