### ISSUE TITLE
Missing packages libmariadb-dev-compat and rustc

### ISSUE THREAD

**Issue by rpauwels** [YunoHost-Apps/homeassistant_ynh#85]
### Describe the bug

After taking a while on a clean install in Docker from domainelibre/yunohost-arm, installation of Home Assistant fails. It appears `mysql_config` and `rustc` were missing. Running `apt install libmariadb-dev-compat rustc` resolved the problem.

### Context

- Hardware: Raspberry Pi 3B at home
- YunoHost version: 4.3.6.3
- I have access to my server: through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: it is running as a Docker instance
- Using, or trying to install package version/branch: 2022.3.8~ynh1

### Steps to reproduce

```sh
sudo yunohost app install homeassistant
```
As I couldn't make out the real problem from the logs, I executed all commands from the failing command one by one. 

`pip --cache-dir /home/yunohost.app/homeassistant/.cache install --upgrade mysqlclient` was the first to give an error:

```
Collecting mysqlclient
  Downloading mysqlclient-2.1.0.tar.gz (87 kB)
     |████████████████████████████████| 87 kB 3.6 MB/s
    ERROR: Command errored out with exit status 1:
     command: /var/www/homeassistant/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lix74cy8/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lix74cy8/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-afd6s79x
         cwd: /tmp/pip-install-lix74cy8/mysqlclient/
    Complete output (15 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lix74cy8/mysqlclient/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-lix74cy8/mysqlclient/setup_posix.py", line 70, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-lix74cy8/mysqlclient/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    mysql_config --version
    mariadb_config --version
    mysql_config --libs
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I executed `apt install libmariadb-dev-compat` to have `mysql_config` available.

Then, `pip --cache-dir /home/yunohost.app/homeassistant/.cache install --upgrade homeassistant==2022.3.8` gave:

```
  ERROR: Command errored out with exit status 1:
   command: /var/www/homeassistant/bin/python3.9 /var/www/homeassistant/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpprnbiagx
       cwd: /tmp/pip-install-cbf3tcym/cryptography
  Complete output (168 lines):
  running bdist_wheel
  running build
  running build_py
[...]
  copying src/cryptography/hazmat/bindings/_rust/x509.pyi -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings/_rust
  running build_ext
  running build_rust
[...]
error: can't find Rust compiler

  If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
```
Running `apt install rustc` allowed me to successfully install Home Assitant.

### Logs

https://paste.yunohost.org/raw/eqavegifih

**Comment by ewilly** [comment]
Hello,
libmariadb-dev-compat is already in dependencies did you uninstall it manually ?
regarding rustc it is normally not necessary but will add it

**Comment by rpauwels** [comment]
Hi, thank you! Indeed it is only rustc that seemed necessary to install (due to cryptography), I was not aware of the rollback that must have uninstalled libmariadb-dev-compat after the error.
