### ISSUE TITLE
Add "external_url" to the default scripted configuration

### ISSUE THREAD

**Issue by DJPlaya** [YunoHost-Apps/homeassistant_ynh#90]
Related to #34 ive had to configure "external_url" in the configuration.yaml of Home Assistant to get HACS working.
This could and should be done automatically when installing and changing domains to make it easy and reduce confusion for the end user.

**Comment by ewilly** [comment]
I use HACS too and no need on my side to add "external_url" and didn't find information about that requirement... where did you find that information ?

**Comment by DJPlaya** [comment]
I partwise got the idea from the HA docs, aswell as some Threads related to reverse proxies > https://www.home-assistant.io/docs/configuration/basic/
I assume the problem may have appeard since the domain i was using havent had reverse DNS records, 
Since changed, HACS seems to be doing fine without it.

**Comment by ewilly** [comment]
#102
